@startuml diagram
title Алгоритм функции predict_user_based_k_fract_mean

start

:'Вычисление средних оценок для каждого пользователя';

repeat
  :Извлечение оценок пользователя i из матрицы тренировочных данных;
  :Определение фильмов с ненулевыми оценками;
  if (Есть оценки фильмов у пользователя i?) then (Да)
    :Вычисление средней оценки фильмов пользователя i;
  else (Нет)
    :Средняя оценка фильмов у пользователя i равна 0;
  endif
repeat while (i < n_users)

:Создание нулевой матрицы предсказаний [пользователи × фильмы];

repeat
  :Сортировка пользователей по убыванию схожести с пользователем i;
  :Выбор top пользователей с наибольшей схожестью;
  :Сохранение значений схожести выбранных пользователей в similarities и средней оценки пользователя i в current_user_mean;
  :Создание временных массивов для взвешенной суммы и суммы схожестей;

  repeat
    :Вычисление средней оценки фильмов пользователя j и сохранение в similar_user_mean;
    :Нормализованная оценка фильма = оценка фильма - similar_user_mean;
    :Обновление значений для взвешенной суммы и суммы схожестей;
  repeat while (j < len(similarities))

  repeat
    if (Сумма схожестей у movie_idx > 0?) then (Да)
      :pred[i, movie_idx] = current_user_mean + (взвешенная сумма / сумма схожестей);
    else (Нет)
      :pred[i, movie_idx] = current_user_mean;
    endif
  repeat while (movie_idx < n_movies)

  :Ограничение предсказанных оценок в диапазон [0, 10];
repeat while (i < n_users)

stop
@enduml