# Generated by Django 5.1.6 on 2025-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.TextField()),
                ('movie_year', models.IntegerField()),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('poster_link', models.TextField(blank=True, null=True)),
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
                ('certificate', models.TextField(blank=True, null=True)),
                ('runtime', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('meta_score', models.IntegerField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('star1', models.TextField(blank=True, null=True)),
                ('star2', models.TextField(blank=True, null=True)),
                ('star3', models.TextField(blank=True, null=True)),
                ('star4', models.TextField(blank=True, null=True)),
                ('votes', models.BigIntegerField(blank=True, null=True)),
                ('gross', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
