# Generated by Django 5.1.6 on 2025-04-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_link', models.TextField(blank=True, null=True)),
                ('movie_name', models.TextField()),
                ('year', models.IntegerField()),
                ('certificate', models.TextField(blank=True, null=True)),
                ('runtime', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('meta_score', models.IntegerField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('star1', models.TextField(blank=True, null=True)),
                ('star2', models.TextField(blank=True, null=True)),
                ('star3', models.TextField(blank=True, null=True)),
                ('star4', models.TextField(blank=True, null=True)),
                ('votes', models.BigIntegerField(blank=True, null=True)),
                ('gross', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': True,
                'unique_together': {('movie_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
            options={
                'db_table': 'favorite',
                'managed': True,
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
