# Generated by Django 5.1.6 on 2025-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('rating', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('released', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('votes', models.FloatField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('star', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('gross', models.FloatField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
