# Generated by Django 5.1.6 on 2025-04-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gross',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='votes',
        ),
    ]
