# Generated by Django 5.1.6 on 2025-04-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_movie_certificate_remove_movie_gross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
