# Generated by Django 5.1.6 on 2025-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.TextField()),
                ('movie_year', models.IntegerField()),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
    ]
