# Generated by Django 5.1.6 on 2025-04-11 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_favorite_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
