# Generated by Django 5.1.6 on 2025-07-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_favorite_user_rating_movierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
