# Generated by Django 5.1.6 on 2025-10-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_country_director_genre_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.IntegerField(blank=True, choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], null=True, verbose_name='Возрастной рейтинг'),
        ),
    ]
