# Generated by Django 5.1.6 on 2026-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_movie_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='local_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Локальная ссылка на постер'),
        ),
    ]
